COMP_NAME = Merger

all: $(COMP_NAME)Comp

SRCS += $(COMP_NAME).cpp
SRCS += $(COMP_NAME)Comp.cpp
#SRCS += CAENv1718.cpp
#SRCS += CAENModule.cpp

#LDLIBS += -l CAENVME -l ncurses
CPPFLAGS += -I.
CPPFLAGS += -I../../util 
CPPFLAGS += -std=c++11

#LDLIBS += -L$(PWD)/../../util -lHexDump -Wl,-rpath=$(PWD)/../../util
# sample install target
#
# MODE = 0755
# BINDIR = /tmp/mybinary
#
# install: $(COMP_NAME)Comp
#	mkdir -p $(BINDIR)
#	install -m $(MODE) $(COMP_NAME)Comp $(BINDIR)

include /usr/share/daqmw/mk/comp.mk
