all:
	$(MAKE) -C DAQLogger all;
	$(MAKE) -C Monitor all;
	$(MAKE) -C BestEffortDispatcher all;
	$(MAKE) -C Merger all;
	$(MAKE) -C Drs4QdcReader1 all;
	$(MAKE) -C MznHRTdcReader1 all;
	$(MAKE) -C MznHRTdcReader2 all;
	$(MAKE) -C MznHRTdcReader3 all;
	
clean:
	$(MAKE) -C DAQLogger clean;
	$(MAKE) -C Monitor clean;
	$(MAKE) -C BestEffortDispatcher clean;
	$(MAKE) -C Merger clean;
	$(MAKE) -C Drs4QdcReader1 clean;
	$(MAKE) -C MznHRTdcReader1 clean;
	$(MAKE) -C MznHRTdcReader2 clean;
	$(MAKE) -C MznHRTdcReader3 clean;
